#!/usr/bin/env python
# -*- coding: utf-8 -*-
r'''
Author:         {author}
Email:          {email}
Date:           {date}
Description:

{module_dot_path} is... TODO: lorem ipsum
{default_description}

Updates:
    {date} - {module_dot_path} - initial commit
'''

# stdlib imports
from __future__ import absolute_import, print_function, division, with_statement  # , unicode_literals
import os
import sys
import logging{stdlib_import}

# third party imports{third_import}

# project imports

SCRIPT_RELPATH = '{script_relpath}'
if not hasattr(sys, '_MEIPASS'):
    SCRIPT_FILEPATH = os.path.abspath(__file__)
else:
    SCRIPT_FILEPATH = os.path.abspath(os.path.join(sys._MEIPASS, SCRIPT_RELPATH))  # pylint: disable=no-member
SCRIPT_DIRPATH = os.path.dirname(SCRIPT_FILEPATH)
SCRIPT_NAME = os.path.splitext(os.path.basename(__file__))[0]
THIS_MODULE = sys.modules[__name__]
LOGGER = logging.getLogger(__name__)
LOGGER.addHandler(logging.NullHandler())
